name: PIMS Logging CI

on:
  push:
    branches: [master, test, dev]
  pull_request:
    branches: [master, test, dev]


jobs:

  build:

    name: build-logging
    if: github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/test' || github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    env:
      SLEEP_TIME: 60
      STORAGE_TYPE: Amazon_S3
      AWS_HOST: moti-int.objectstore.gov.bc.ca
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_BUCKET_NAME: tran_api_psp_logfiles_dev
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FRONTEND_APP_NAME: pims-app
      API_NAME: pims-api
      PROJECT_NAMESPACE: 3cd915-dev
      EXPORT_TIME: 120
      OC_TOKEN: ${{ secrets.OC_TOKEN }}
      OC_SERVICEACCOUNT_TOKEN: ${{ secrets.OC_SERVICEACCOUNT_TOKEN }}
      OC_SERVER: https://api.silver.devops.gov.bc.ca:6443
      working-directory: ./openshift/4.0/templates/Logging

    steps:
    - uses: actions/checkout@v4
    - name: Set ENV variable
      run: |
        if [[ ${{github.event.ref}} == 'refs/heads/test' ]]; then
            echo "FRONTEND_APP_NAME=pims-app-test" >> $GITHUB_ENV
            echo "API_NAME=pims-api-test" >> $GITHUB_ENV
        elif [[ ${{github.event.ref}} == 'refs/heads/master' ]]; then
           echo "FRONTEND_APP_NAME=pims-app-uat" >> $GITHUB_ENV
           echo "API_NAME=pims-api-uat" >> $GITHUB_ENV
           echo "PROJECT_NAMESPACE=3cd915-test" >> $GITHUB_ENV
        else
            echo "FRONTEND_APP_NAME=pims-app" >> $GITHUB_ENV
            echo "API_NAME=pims-api" >> $GITHUB_ENV
        fi
    - name: Build the pims-logging docker-compose stack
      run: docker-compose -f docker-compose.yml up -d
      working-directory: ${{env.working-directory}}
    - name: Sleep for 180 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '180s'
    - name: Check Extracted Logs
      run: |
        docker cp pims-logging:/logging/. .
        exitcode=$(docker inspect pims-logging --format='{{.State.ExitCode}}')
        if [[ "$(ls -A pims* 2>/dev/null | wc -l)" != "0" ]]; then
            ls -A pims* && rm -f pims*
        elif [[ $exitcode == 0 ]]; then
            echo "Info: No log captured between sleep time"
        else
            echo "There's an error capturing pims logs" && exit 1
        fi
    - name: Check running containers
      run: docker ps -a
    - name: Check pims-logging logs
      if: always()
      run: docker logs pims-logging
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
      working-directory: ${{env.working-directory}}
